Integration tests
wacoo/blog-front-ruby-rails pull request #8
Opened 2023-11-14 19:33 UTC by wacoo

- Fix code to prevent N+1 query problem
- Add integration test for user
- Add integration test for post

Screenshots
==========
Before
=====
![bf](https://github.com/wacoo/blog-front-ruby-rails/assets/9458141/3e35d536-f124-4a16-bf5c-38e955e22315)

After
====
![af](https://github.com/wacoo/blog-front-ruby-rails/assets/9458141/db395716-2251-4c0d-b1a9-034c8e2638a8)

2023-11-14 21:00 UTC, frank1738 requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


<img src="https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

## Highlights

✅ Tested Most scenarios
✅Polished and Professional documentation
✅ Fixed the `N+1` problem👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-14 21:00 UTC, frank1738 commented on spec/user_integraion_spec.rb
> +      expect(page).to have_css('img[src="https://media.giphy.com/media/tZaFa1m8UfzXy/giphy.gif"]')
- [ ] on your `user#show` tests, Kindly add :
  - Tests that asserts you can see the user's first 3 posts.

2023-11-14 21:00 UTC, frank1738 commented on spec/post_integraion_spec.rb
> +                bio: 'This is John\'s bio', posts_counter: 0)
- [ ] on your `post#index` tests, Kindly add :
  - Tests that asserts you can see a section for pagination if there are more posts than fit on the view.

2023-11-14 21:00 UTC, frank1738 commented on spec/post_integraion_spec.rb
> +    @cmt2 = Comment.create(user: @user2, post: @post2, text: 'Hey great post!')
#### 🌟 Optional Suggestion 

- [ ] Consider organizing your feature tests within a feature folder. For each feature (e.g., Users), create a dedicated folder (e.g., users) and inside it, have `index`and `show` files to test corresponding views. This approach enhances code organization, separates concerns, and makes maintenance a breeze! 🚀

#### Example
```
📁 spec
  📁 features
    📁 users
      📄 index_spec.rb
      📄 show_spec.rb
    📁 posts
      📄 index_spec.rb
      📄 show_spec.rb


```

#### Keep up with the good work! 🌟✨

2023-11-15 07:21 UTC, MahmoudBakr23 approved these changes
Hi team😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

**Highlights**
- Well done on addressing the requested changes from the previous reviewer

Cheers, and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-15 09:16 UTC, merged